imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
#doctrine:
#    dbal:
#        driver:   %database_driver%
#        host:     %database_host%
#        port:     %database_port%
#        dbname:   %database_name%
#        user:     %database_user%
#        password: %database_password%
#        charset:  UTF8

#    orm:
#        auto_generate_proxy_classes: %kernel.debug%
#        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: gmail
    username:  %mailer_user%
    password:  %mailer_password%

#jms_security_extra:
#    secure_controllers:  true
#   secure_all_services: false

fos_user:
    db_driver:         propel # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name:     main
    user_class:        FOS\UserBundle\Propel\UserProxy
    propel_user_class: FOS\UserBundle\Propel\User

    from_email:
        address:     fpondepeyre@gmail.com
        sender_name: Dyt#

    registration:
        confirmation:
            enabled:    true
            from_email:
                address:     fpondepeyre@gmail.com
                sender_name: Dyt

    resetting:
        email:
            from_email:
                address:     fpondepeyre@gmail.com
                sender_name: Dyt

    service:
       mailer: fos_user.mailer.twig_swift

#stof_doctrine_extensions:
#    orm:
#        default:
#            timestampable: true

propel:
    # The next two lines are useless if you are using Composer
    # to manage your dependencies
    path:       "%kernel.root_dir%/../vendor/propel"
    phing_path: "%kernel.root_dir%/../vendor/phing"

mopa_bootstrap:
    form:
        show_legend: false # default is true
        show_child_legend: true # default is true
        error_type: inline # or inline which is default