imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

propel:
    dbal:
        driver:               mysql
        user:                 %database_user%
        password:             %database_password%
        dsn:                  mysql:host=%database_host%;dbname=%database_name%;charset=UTF8
        options:              {}
        attributes:           {}