parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: dyt
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 3e5eec80159ce0931fedbecdd272b72a5b20bde1
    database_path: null
